//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACOTACIONE
    {
        public short AcoCod { get; set; }
        public string AcoDsc { get; set; }
        public string AcoAbr { get; set; }
        public short AcoUsuCodCre { get; set; }
        public System.DateTime AcoFchCre { get; set; }
        public Nullable<short> AcoUsuCodMod { get; set; }
        public Nullable<System.DateTime> AcoFchMod { get; set; }
        public short AcoCol { get; set; }
        public Nullable<short> AcoCol3 { get; set; }
        public Nullable<short> AcoCol2 { get; set; }
        public Nullable<short> AcoCol1 { get; set; }
        public Nullable<decimal> AcoMon { get; set; }
    }
}
