//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVOSZONA
    {
        public short ActAntCod { get; set; }
        public string ActAnt { get; set; }
        public string ActSubAnt { get; set; }
        public string ActSubAct { get; set; }
        public string ActActu { get; set; }
    }
}
