//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVOSPEMEX
    {
        public short ActPmx { get; set; }
        public string ActPmxAnt { get; set; }
        public string SubDirAnt { get; set; }
        public string ActActPmx { get; set; }
        public string SubSDirAct { get; set; }
    }
}
