//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVOSRESGUARDO
    {
        public int ActCod { get; set; }
        public short ActConCod { get; set; }
        public short ActFamCod { get; set; }
        public int ResgEmpCod { get; set; }
        public short ResgEmpComCod { get; set; }
        public Nullable<System.DateTime> ResgFch { get; set; }
        public short ResgAct { get; set; }
        public byte[] ResgArc { get; set; }
        public string ResgArcTip { get; set; }
        public string ResgArcNom { get; set; }
    }
}
