//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVO
    {
        public int ActCod { get; set; }
        public short ActConCod { get; set; }
        public short ActFamCod { get; set; }
        public short UneCod { get; set; }
        public string ActTip { get; set; }
        public short ActMod { get; set; }
        public string ActPla { get; set; }
        public string ActSer { get; set; }
        public string ActPol { get; set; }
        public string ActUni { get; set; }
        public string ActDsc { get; set; }
        public short ActMarCod { get; set; }
        public byte[] ActFot { get; set; }
        public string ActFotNom { get; set; }
        public string ActFotTip { get; set; }
        public Nullable<short> ActSfaCod { get; set; }
        public Nullable<System.DateTime> ActFchAdq { get; set; }
        public string ActFac { get; set; }
        public Nullable<short> ActUneCod { get; set; }
        public Nullable<decimal> ActMoi { get; set; }
        public Nullable<short> EstCod { get; set; }
        public string ActCtaAct { get; set; }
        public string ActSAN { get; set; }
        public string ActPIN { get; set; }
        public string ActSITE { get; set; }
        public Nullable<short> ActAct { get; set; }
        public short ActDepCod { get; set; }
        public string ActObs { get; set; }
        public byte[] ActArcFac { get; set; }
        public string ActArcFacNom { get; set; }
        public string ActArcFacTip { get; set; }
    }
}
