//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADJUNTO_CAPA
    {
        public int AdCapCod { get; set; }
        public int CapCod { get; set; }
        public System.DateTime AdCapFch { get; set; }
        public byte[] AdCapArc { get; set; }
        public string AdCapArcTip { get; set; }
        public string AdCapArcNom { get; set; }
        public short AdCapTip { get; set; }
        public short AdCapUsuCodCre { get; set; }
        public System.DateTime AdCapFchCre { get; set; }
        public Nullable<short> AdCapUsuCodMod { get; set; }
        public Nullable<System.DateTime> AdCapFchMod { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    }
}
