//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTOMATICO
    {
        public short AutCod { get; set; }
        public short MovTipDoc { get; set; }
        public System.DateTime AutFchCre { get; set; }
        public short AutUsuCod { get; set; }
        public Nullable<System.DateTime> AutFchMod { get; set; }
        public Nullable<short> AutUsuCodMod { get; set; }
        public short AutLin { get; set; }
        public short AutTie { get; set; }
        public short AutTip { get; set; }
    }
}
