//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANCO
    {
        public short BanCod { get; set; }
        public string BanNom { get; set; }
        public System.DateTime BanFchCre { get; set; }
        public short BanUsuCodCre { get; set; }
        public System.DateTime BanFchMod { get; set; }
        public short BanUsuCodMod { get; set; }
    }
}
