//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE
    {
        public short BasCod { get; set; }
        public string BasNom { get; set; }
        public System.DateTime BasFchCre { get; set; }
        public short BasUsuCodCre { get; set; }
        public System.DateTime BasFchMod { get; set; }
        public short BasUsuCodMod { get; set; }
        public string BasAbr { get; set; }
        public string BasDim { get; set; }
    }
}
