//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPACITACIONESASISTENCIA
    {
        public int CapCod { get; set; }
        public int AsiEmpCod { get; set; }
        public short AsiEmpComCod { get; set; }
        public short AsiAsi { get; set; }
        public short AsiApr { get; set; }
        public string AsiNot { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    }
}
