//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPACITAR
    {
        public int CapaCod { get; set; }
        public short CapaMes { get; set; }
        public short CapaAno { get; set; }
        public short CapaUsuCod { get; set; }
        public int CapaResEmpCod { get; set; }
        public int CapaSupEmpCod { get; set; }
        public int CapaRepEmpCod { get; set; }
        public short CapaResComCod { get; set; }
        public short CapaSupComCod { get; set; }
        public short CapaRepComCod { get; set; }
        public string CapaAct { get; set; }
        public string CapaCon { get; set; }
        public short CapaBasCod { get; set; }
        public int CapaCurCod { get; set; }
    }
}
