//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPACITACIONE
    {
        public int CapCod { get; set; }
        public short CapConCod { get; set; }
        public string CapFol { get; set; }
        public Nullable<System.DateTime> CapFch { get; set; }
        public Nullable<short> CapEst { get; set; }
        public Nullable<int> CurCod { get; set; }
        public Nullable<int> CapProEmpCod { get; set; }
        public Nullable<int> CapRevEmpCod { get; set; }
        public Nullable<int> CapAutEmpCod { get; set; }
        public Nullable<int> CapInsEmpCod { get; set; }
        public Nullable<short> CapEqu { get; set; }
        public Nullable<int> CapLocCod { get; set; }
        public Nullable<System.DateTime> CapFchIni { get; set; }
        public Nullable<System.DateTime> CapFchTer { get; set; }
        public string CapNotPro { get; set; }
        public string CapNot { get; set; }
        public Nullable<int> CapTecEmpCod { get; set; }
        public System.DateTime CapFchNot { get; set; }
        public Nullable<int> CapResEmpCod { get; set; }
        public Nullable<int> CapAteEmpCod { get; set; }
        public string CapAct { get; set; }
        public string CapCon { get; set; }
        public Nullable<int> CapFirEmpCod { get; set; }
        public short CapUsuCodCre { get; set; }
        public System.DateTime CapFchCre { get; set; }
        public Nullable<short> CapUsuCodMod { get; set; }
        public Nullable<System.DateTime> CapFchMod { get; set; }
        public Nullable<short> CapProEmpComCod { get; set; }
        public Nullable<short> CapRevEmpComCod { get; set; }
        public Nullable<short> CapAutEmpComCod { get; set; }
        public Nullable<short> CapInsEmpComCod { get; set; }
        public Nullable<short> CapTecEmpComCod { get; set; }
        public Nullable<short> CapResEmpComCod { get; set; }
        public Nullable<short> CapAteEmpComCod { get; set; }
        public Nullable<short> CapFirEmpComCod { get; set; }
        public Nullable<int> CapaCod { get; set; }
    }
}
