//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPTURAPRESUPUESTO
    {
        public short PreCod { get; set; }
        public System.DateTime PreFch { get; set; }
        public int PreLocCod { get; set; }
        public short TPrCod { get; set; }
        public decimal PreMon { get; set; }
    }
}
