//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIERRE
    {
        public short CieAno { get; set; }
        public Nullable<short> CieEne { get; set; }
        public Nullable<short> CieFeb { get; set; }
        public Nullable<short> CieMar { get; set; }
        public Nullable<short> CieAbr { get; set; }
        public Nullable<short> CieMay { get; set; }
        public Nullable<short> CieJun { get; set; }
        public Nullable<short> CieJul { get; set; }
        public Nullable<short> CieAgo { get; set; }
        public Nullable<short> CieSep { get; set; }
        public Nullable<short> CieOct { get; set; }
        public Nullable<short> CieNov { get; set; }
        public Nullable<short> CieDic { get; set; }
    }
}
