//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIUDADE
    {
        public short CiuCod { get; set; }
        public System.DateTime CiuFchCre { get; set; }
        public short CiuUsuCodCre { get; set; }
        public System.DateTime CiuFchMod { get; set; }
        public short CiuUsuCodMod { get; set; }
        public short MunCod { get; set; }
        public string CiuDsc { get; set; }
    }
}
