//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANIA
    {
        public short ComCod { get; set; }
        public string ComDoc { get; set; }
        public string ComTip { get; set; }
        public Nullable<System.DateTime> ComFchCre { get; set; }
        public Nullable<short> ComUsuCodCre { get; set; }
        public Nullable<System.DateTime> ComFchMod { get; set; }
        public Nullable<short> ComUsuCodMod { get; set; }
        public string ComNom { get; set; }
        public byte[] ComLog { get; set; }
    }
}
