//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATOCONVENIO
    {
        public short ConCod { get; set; }
        public string ConvCod { get; set; }
        public decimal ConvMon { get; set; }
        public System.DateTime ConvFchIni { get; set; }
        public System.DateTime ConvFchTer { get; set; }
        public string ConvDsc { get; set; }
        public short ConvTip { get; set; }
    }
}
