//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTENEDORE
    {
        public short ContCod { get; set; }
        public int RegLocCod { get; set; }
        public int UniLocCod { get; set; }
        public string ContNum { get; set; }
        public short ContTbx { get; set; }
        public short ContTip { get; set; }
    }
}
