//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTRATO()
        {
            this.ESTIMACIONs = new HashSet<ESTIMACION>();
            this.EVIDENCIAS = new HashSet<EVIDENCIA>();
        }
    
        public short ConCod { get; set; }
        public string ConNum { get; set; }
        public string ConDsc { get; set; }
        public System.DateTime ConFchIni { get; set; }
        public System.DateTime ConFchTer { get; set; }
        public decimal ConMon { get; set; }
        public Nullable<System.DateTime> ConFchCre { get; set; }
        public Nullable<short> ConUsuCodCre { get; set; }
        public Nullable<System.DateTime> ConFchMod { get; set; }
        public Nullable<short> ConUsuCodMod { get; set; }
        public short ComCod { get; set; }
        public string ConTipMon { get; set; }
        public int ConAcrSAP { get; set; }
        public string ConNumSAP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTIMACION> ESTIMACIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVIDENCIA> EVIDENCIAS { get; set; }
    }
}
