//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACOTACIONE> ACOTACIONES { get; set; }
        public virtual DbSet<ACTIVO> ACTIVOS { get; set; }
        public virtual DbSet<ACTIVOSLOC> ACTIVOSLOCs { get; set; }
        public virtual DbSet<ACTIVOSPEMEX> ACTIVOSPEMEXes { get; set; }
        public virtual DbSet<ACTIVOSPROGMANTTO> ACTIVOSPROGMANTTOes { get; set; }
        public virtual DbSet<ACTIVOSRESGUARDO> ACTIVOSRESGUARDOes { get; set; }
        public virtual DbSet<ACTIVOSZONA> ACTIVOSZONAs { get; set; }
        public virtual DbSet<ADJUNTO_CAPA> ADJUNTO_CAPA { get; set; }
        public virtual DbSet<AFECTACIONE> AFECTACIONES { get; set; }
        public virtual DbSet<ALMACENE> ALMACENES { get; set; }
        public virtual DbSet<ARTICULOSEDI> ARTICULOSEDIS { get; set; }
        public virtual DbSet<AUTOMATICO> AUTOMATICOes { get; set; }
        public virtual DbSet<AUTOMATICOCORREOAUT> AUTOMATICOCORREOAUTs { get; set; }
        public virtual DbSet<BANCO> BANCOes { get; set; }
        public virtual DbSet<BASE> BASEs { get; set; }
        public virtual DbSet<BASEBASECOORD> BASEBASECOORDs { get; set; }
        public virtual DbSet<CAPACITACIONE> CAPACITACIONES { get; set; }
        public virtual DbSet<CAPACITACIONESASISTENCIA> CAPACITACIONESASISTENCIAs { get; set; }
        public virtual DbSet<CAPACITAR> CAPACITARs { get; set; }
        public virtual DbSet<CAPACITARPDA> CAPACITARPDAS { get; set; }
        public virtual DbSet<CAPTURAPRESUPUESTO> CAPTURAPRESUPUESTOes { get; set; }
        public virtual DbSet<CAUSA> CAUSAS { get; set; }
        public virtual DbSet<CIERRE> CIERREs { get; set; }
        public virtual DbSet<CIUDADE> CIUDADES { get; set; }
        public virtual DbSet<CLASIVTA> CLASIVTAs { get; set; }
        public virtual DbSet<COMPANIA> COMPANIAs { get; set; }
        public virtual DbSet<CONTENEDORE> CONTENEDORES { get; set; }
        public virtual DbSet<CONTRATO> CONTRATOes { get; set; }
        public virtual DbSet<CONTRATOCONVENIO> CONTRATOCONVENIOs { get; set; }
        public virtual DbSet<COORDINADORE> COORDINADORES { get; set; }
        public virtual DbSet<CURSO> CURSOS { get; set; }
        public virtual DbSet<CURSOSDETALLE> CURSOSDETALLEs { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTOes { get; set; }
        public virtual DbSet<DETALLELOG> DETALLELOGs { get; set; }
        public virtual DbSet<DIPLOMA> DIPLOMAS { get; set; }
        public virtual DbSet<DISTRIBUCIONCONVENIO> DISTRIBUCIONCONVENIOs { get; set; }
        public virtual DbSet<DOCUMENTO> DOCUMENTOS { get; set; }
        public virtual DbSet<DOCUMENTOSPERMISO> DOCUMENTOSPERMISOS { get; set; }
        public virtual DbSet<EDI> EDIs { get; set; }
        public virtual DbSet<EMPCONTRATO> EMPCONTRATOS { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADOS { get; set; }
        public virtual DbSet<EMPLEADOSFAMILIA> EMPLEADOSFAMILIAs { get; set; }
        public virtual DbSet<ENVIARCORREO> ENVIARCORREOS { get; set; }
        public virtual DbSet<ESTADO> ESTADOes { get; set; }
        public virtual DbSet<ESTATU> ESTATUS { get; set; }
        public virtual DbSet<ESTIMACION> ESTIMACIONs { get; set; }
        public virtual DbSet<ESTIMACIONDETALLE> ESTIMACIONDETALLEs { get; set; }
        public virtual DbSet<EVIDENCIA> EVIDENCIAS { get; set; }
        public virtual DbSet<FAMILIA> FAMILIAS { get; set; }
        public virtual DbSet<FAMILIASSUBFAMILIA> FAMILIASSUBFAMILIAs { get; set; }
        public virtual DbSet<FINIQUITO> FINIQUITOS { get; set; }
        public virtual DbSet<GASOLINA> GASOLINAs { get; set; }
        public virtual DbSet<GERENCIA> GERENCIAS { get; set; }
        public virtual DbSet<GUARDIA> GUARDIAS { get; set; }
        public virtual DbSet<GUARDIASUBICACION> GUARDIASUBICACIONs { get; set; }
        public virtual DbSet<INCIDENCIA> INCIDENCIAs { get; set; }
        public virtual DbSet<INVENTARIO> INVENTARIOs { get; set; }
        public virtual DbSet<INVENTARIOTEMP> INVENTARIOTEMPs { get; set; }
        public virtual DbSet<LICENCIA> LICENCIAS { get; set; }
        public virtual DbSet<LOCALIZACIONE> LOCALIZACIONES { get; set; }
        public virtual DbSet<LOG> LOGs { get; set; }
        public virtual DbSet<Loger> Logers { get; set; }
        public virtual DbSet<LogersDetalle> LogersDetalles { get; set; }
        public virtual DbSet<MANTTOEVIDENCIA> MANTTOEVIDENCIAs { get; set; }
        public virtual DbSet<MANTTOEVIDENCIADETALLE> MANTTOEVIDENCIADETALLEs { get; set; }
        public virtual DbSet<MANTTOPROGRAMADA> MANTTOPROGRAMADAS { get; set; }
        public virtual DbSet<MANTTOREF> MANTTOREFs { get; set; }
        public virtual DbSet<MARCA> MARCAs { get; set; }
        public virtual DbSet<MEDIDA> MEDIDAS { get; set; }
        public virtual DbSet<MENU> MENUS { get; set; }
        public virtual DbSet<MOVIMIENTO> MOVIMIENTOS { get; set; }
        public virtual DbSet<MOVIMIENTOSDETALLE> MOVIMIENTOSDETALLEs { get; set; }
        public virtual DbSet<MOVIMIENTOSDETALLESUBPDA> MOVIMIENTOSDETALLESUBPDAs { get; set; }
        public virtual DbSet<MUNICIPIO> MUNICIPIOS { get; set; }
        public virtual DbSet<NOMINA> NOMINAs { get; set; }
        public virtual DbSet<NOMINAEMPRESA> NOMINAEMPRESAs { get; set; }
        public virtual DbSet<NOTAINFORMATIVA> NOTAINFORMATIVAs { get; set; }
        public virtual DbSet<NOTAINFORMATIVADETALLE> NOTAINFORMATIVADETALLEs { get; set; }
        public virtual DbSet<NOTAINFORMATIVADETALLESUBPDA> NOTAINFORMATIVADETALLESUBPDAs { get; set; }
        public virtual DbSet<OCUPACIONCONTENEDORE> OCUPACIONCONTENEDORES { get; set; }
        public virtual DbSet<OPERATIVO> OPERATIVOes { get; set; }
        public virtual DbSet<OrdenServicio> OrdenServicios { get; set; }
        public virtual DbSet<OrdenServicioDesglose> OrdenServicioDesgloses { get; set; }
        public virtual DbSet<OrdenServicioMonto> OrdenServicioMontoes { get; set; }
        public virtual DbSet<OrdenServicioRaf> OrdenServicioRafs { get; set; }
        public virtual DbSet<OrdenServicioRafEstatu> OrdenServicioRafEstatus { get; set; }
        public virtual DbSet<Pedido> Pedidos { get; set; }
        public virtual DbSet<PERFILE> PERFILES { get; set; }
        public virtual DbSet<PERFILESAPLICATIVO> PERFILESAPLICATIVOes { get; set; }
        public virtual DbSet<PERMISOSMENU> PERMISOSMENUs { get; set; }
        public virtual DbSet<POLITICA> POLITICAS { get; set; }
        public virtual DbSet<POLITICASENTREGA> POLITICASENTREGAs { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTOS { get; set; }
        public virtual DbSet<PRODUCTOSSUBPRODUCTO> PRODUCTOSSUBPRODUCTOes { get; set; }
        public virtual DbSet<PRODUCTOSUBICACION> PRODUCTOSUBICACIONs { get; set; }
        public virtual DbSet<PRODUCTOSUBICACIONODOMETRO> PRODUCTOSUBICACIONODOMETROes { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDORs { get; set; }
        public virtual DbSet<PUESTO> PUESTOes { get; set; }
        public virtual DbSet<REGISTRO> REGISTROes { get; set; }
        public virtual DbSet<REQUISICION> REQUISICIONs { get; set; }
        public virtual DbSet<REQUISICIONDETALLE> REQUISICIONDETALLEs { get; set; }
        public virtual DbSet<REQUISICIONESTATU> REQUISICIONESTATUS { get; set; }
        public virtual DbSet<RES_ACTIVOS> RES_ACTIVOS { get; set; }
        public virtual DbSet<RESGUARDO> RESGUARDOS { get; set; }
        public virtual DbSet<RESGUARDOSDETALLERE> RESGUARDOSDETALLERES { get; set; }
        public virtual DbSet<SEGURIDAD> SEGURIDADs { get; set; }
        public virtual DbSet<SEGURIDADORDEN> SEGURIDADORDENs { get; set; }
        public virtual DbSet<SOLICITUDESPEMEX> SOLICITUDESPEMEXes { get; set; }
        public virtual DbSet<SOLICITUV> SOLICITUVs { get; set; }
        public virtual DbSet<STATUSRAF> STATUSRAFs { get; set; }
        public virtual DbSet<Subdireccione> Subdirecciones { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TIPOCONDETALLE> TIPOCONDETALLEs { get; set; }
        public virtual DbSet<TIPOCONT> TIPOCONTs { get; set; }
        public virtual DbSet<TIPODOC> TIPODOCs { get; set; }
        public virtual DbSet<TIPOPROD> TIPOPRODs { get; set; }
        public virtual DbSet<UBICACION> UBICACIONs { get; set; }
        public virtual DbSet<UNEGOCIO> UNEGOCIOs { get; set; }
        public virtual DbSet<USUARIO> USUARIOS { get; set; }
        public virtual DbSet<USUARIOSCOMPONENTE> USUARIOSCOMPONENTEs { get; set; }
        public virtual DbSet<VALESAUTORIZADO> VALESAUTORIZADOS { get; set; }
        public virtual DbSet<WEBCOMPONENTE> WEBCOMPONENTES { get; set; }
    }
}
