//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTAMENTO
    {
        public short DepCod { get; set; }
        public string DepDsc { get; set; }
        public short DepConCod { get; set; }
        public Nullable<System.DateTime> DepFchCre { get; set; }
        public Nullable<short> DepUsuCodCre { get; set; }
        public Nullable<System.DateTime> DepFchMod { get; set; }
        public Nullable<short> DepUsuCodMod { get; set; }
        public string DepAbr { get; set; }
    }
}
