//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIPLOMA
    {
        public int DipCod { get; set; }
        public int EmpCod { get; set; }
        public short EmpComCod { get; set; }
        public string DipCom { get; set; }
        public byte[] DipDip { get; set; }
        public string DipDipNom { get; set; }
        public string DipDipTip { get; set; }
        public System.DateTime DipFchCre { get; set; }
        public short DipUsuCre { get; set; }
        public Nullable<System.DateTime> DipFchUpd { get; set; }
        public Nullable<short> DipUsuUpd { get; set; }
        public short DipCla { get; set; }
        public short DipConCod { get; set; }
    }
}
