//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRIBUCIONCONVENIO
    {
        public short DisCod { get; set; }
        public short ConCod { get; set; }
        public string ConvCod { get; set; }
        public int LocUniCod { get; set; }
        public Nullable<decimal> DisMon { get; set; }
        public System.DateTime DisFch { get; set; }
        public Nullable<short> DisTip { get; set; }
        public string DisLocNom { get; set; }
        public Nullable<short> DisDisCod { get; set; }
        public short DisLocTip { get; set; }
    }
}
