//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTO
    {
        public short DocCod { get; set; }
        public System.DateTime DocFch { get; set; }
        public string DocDsc { get; set; }
        public byte[] DocArc { get; set; }
        public string DocTip { get; set; }
        public string DocNom { get; set; }
        public short TidCod { get; set; }
        public Nullable<short> DocDepCod { get; set; }
    }
}
