//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDI
    {
        public short EdyCod { get; set; }
        public int EdySer { get; set; }
        public Nullable<System.DateTime> EdyFchCre { get; set; }
        public Nullable<short> EdyUsuCodCre { get; set; }
        public Nullable<System.DateTime> EdyFchMod { get; set; }
        public Nullable<short> EdyUsuCodMod { get; set; }
        public short EdyConCod { get; set; }
    }
}
