//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPCONTRATO
    {
        public short EmCCod { get; set; }
        public int EmpCod { get; set; }
        public short EmpComCod { get; set; }
        public System.DateTime EmCFchIni { get; set; }
        public System.DateTime EmCFchTer { get; set; }
        public short EmCUsuCodCre { get; set; }
        public System.DateTime EmCFchCre { get; set; }
        public Nullable<short> EmCUsuCodMod { get; set; }
        public Nullable<System.DateTime> EmCFchMod { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    }
}
