//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO()
        {
            this.ENVIARCORREOS = new HashSet<ENVIARCORREO>();
        }
    
        public int EmpCod { get; set; }
        public short EmpComCod { get; set; }
        public byte[] EmpFot { get; set; }
        public string EmpFotNom { get; set; }
        public string EmpFotTip { get; set; }
        public string EmpFic { get; set; }
        public short EmpEst { get; set; }
        public string EmpNom { get; set; }
        public string EmpApePat { get; set; }
        public string EmpApeMat { get; set; }
        public Nullable<short> PueCod { get; set; }
        public Nullable<short> EmpCenCos { get; set; }
        public Nullable<short> EmpBasCod { get; set; }
        public Nullable<decimal> EmpSueMen { get; set; }
        public Nullable<System.DateTime> EmpFchIng { get; set; }
        public Nullable<System.DateTime> EmpFchBaj { get; set; }
        public string EmpMotBaj { get; set; }
        public Nullable<short> EmpNSSAlt { get; set; }
        public string EmpNSS { get; set; }
        public string EmpTipSan { get; set; }
        public string EmpAle { get; set; }
        public Nullable<System.DateTime> EmpFchNac { get; set; }
        public Nullable<short> CiuCod { get; set; }
        public Nullable<short> EmpEstCiv { get; set; }
        public string EmpDom { get; set; }
        public string EmpNoExt { get; set; }
        public string EmpNoInt { get; set; }
        public string EmpCol { get; set; }
        public Nullable<int> EmprCP { get; set; }
        public Nullable<short> EmpCiuCod { get; set; }
        public Nullable<short> EmpSex { get; set; }
        public string EmpRFCHom { get; set; }
        public string EmpCurHom { get; set; }
        public Nullable<short> BanCod { get; set; }
        public string EmpNumTar { get; set; }
        public string EmpCtaBan { get; set; }
        public string EmpCLABE { get; set; }
        public string EmBen { get; set; }
        public string EmpTelCas { get; set; }
        public string EmpTelCel { get; set; }
        public Nullable<decimal> EmpTalBot { get; set; }
        public Nullable<short> EmpTalOve { get; set; }
        public string EmpTalCam { get; set; }
        public string EmpCorEle { get; set; }
        public Nullable<short> EmpGra { get; set; }
        public string EmpTit { get; set; }
        public string EmpCed { get; set; }
        public string EmpRefEmeNom { get; set; }
        public string EmpRefEmeTel { get; set; }
        public Nullable<short> EmpCreInf { get; set; }
        public string EmpCreDat { get; set; }
        public Nullable<System.DateTime> EmpFchCre { get; set; }
        public Nullable<short> EmpUsuCod { get; set; }
        public Nullable<System.DateTime> EmpFchMod { get; set; }
        public Nullable<short> EmpUsuCodMod { get; set; }
        public Nullable<short> EmpAut { get; set; }
        public Nullable<decimal> EmpSalDia { get; set; }
        public Nullable<decimal> EmpSalDiaInt { get; set; }
        public Nullable<short> EmpDepCod { get; set; }
        public Nullable<short> EmpComCodNom { get; set; }
        public string EmpIFE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENVIARCORREO> ENVIARCORREOS { get; set; }
    }
}
