//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOSFAMILIA
    {
        public int EmpCod { get; set; }
        public short EmpComCod { get; set; }
        public short PerFamCod { get; set; }
        public short PerFamSex { get; set; }
        public string PerFamNom { get; set; }
        public System.DateTime PerFamFchNac { get; set; }
    }
}
