//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTATU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESTATU()
        {
            this.EVIDENCIAS = new HashSet<EVIDENCIA>();
            this.NOTAINFORMATIVADETALLEs = new HashSet<NOTAINFORMATIVADETALLE>();
        }
    
        public short EstCod { get; set; }
        public string EstDsc { get; set; }
        public Nullable<System.DateTime> EstFchCre { get; set; }
        public Nullable<short> EstUsuCodCre { get; set; }
        public Nullable<System.DateTime> EstFchMod { get; set; }
        public Nullable<short> EstUsuCodMod { get; set; }
        public string EstMod { get; set; }
        public short EstConCod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVIDENCIA> EVIDENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTAINFORMATIVADETALLE> NOTAINFORMATIVADETALLEs { get; set; }
    }
}
