//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO
    {
        public short EstaCod { get; set; }
        public string EstaNom { get; set; }
        public System.DateTime EstaFchCre { get; set; }
        public short EstaUsuCodCre { get; set; }
        public System.DateTime EstaFchMod { get; set; }
        public short EstaUsuCodMod { get; set; }
        public string EstaAbr { get; set; }
    }
}
