//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTIMACIONDETALLE
    {
        public int EstiCod { get; set; }
        public int EstiDProCod { get; set; }
        public decimal EstiDEst { get; set; }
        public int EstiDAcu { get; set; }
        public Nullable<decimal> EstiDCos { get; set; }
    }
}
