//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAMILIA
    {
        public short FamCod { get; set; }
        public string FamDsc { get; set; }
        public string FamAbr { get; set; }
        public short FamLin { get; set; }
        public short FamConCod { get; set; }
        public Nullable<System.DateTime> FamFchCre { get; set; }
        public Nullable<short> FamUsuCodCre { get; set; }
        public Nullable<System.DateTime> FamFchMod { get; set; }
        public Nullable<short> FamUsuCodMod { get; set; }
        public Nullable<short> FamPorDep { get; set; }
        public short FamCta { get; set; }
    }
}
