//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUARDIA
    {
        public short GuaCod { get; set; }
        public short GuaDia { get; set; }
        public int GuaEmpCod { get; set; }
        public short GuaEmpComCod { get; set; }
        public short GuaUsuCodCre { get; set; }
        public System.DateTime GuaFchCre { get; set; }
        public Nullable<short> GuaUsuMod { get; set; }
        public Nullable<System.DateTime> GuaFchMod { get; set; }
    }
}
