//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUARDIASUBICACION
    {
        public int EmpCod { get; set; }
        public short EmpComCod { get; set; }
        public System.DateTime GubFch { get; set; }
        public short AcoCod { get; set; }
        public short GubUsuCodCre { get; set; }
        public short GubFchCre { get; set; }
        public short GubUsuCodMod { get; set; }
        public short GubFchMod { get; set; }
        public short GubDia { get; set; }
        public string GubEqu { get; set; }
    }
}
