//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIOTEMP
    {
        public int InvCod { get; set; }
        public short AlmCod { get; set; }
        public int ProCod { get; set; }
        public System.DateTime InvFch { get; set; }
        public Nullable<short> SprCod { get; set; }
        public short InvConCod { get; set; }
        public Nullable<decimal> InvSalAju { get; set; }
        public Nullable<decimal> InvEnt { get; set; }
        public Nullable<decimal> InvEntAju { get; set; }
        public Nullable<decimal> InvVen { get; set; }
        public Nullable<decimal> InvDan { get; set; }
        public Nullable<decimal> InvPer { get; set; }
        public Nullable<decimal> InvTra { get; set; }
        public Nullable<decimal> InvTraRec { get; set; }
        public Nullable<decimal> InvTrs { get; set; }
        public Nullable<decimal> InvPre { get; set; }
        public Nullable<decimal> InvCon { get; set; }
    }
}
