//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICENCIA
    {
        public int LicCod { get; set; }
        public System.DateTime PerVigLic { get; set; }
        public int EmpCod { get; set; }
        public short EmpComCod { get; set; }
        public short PerConCod { get; set; }
        public short PerTipLic { get; set; }
        public string PerNoLic { get; set; }
        public short LicEstaCod { get; set; }
        public Nullable<short> LicTip { get; set; }
    }
}
