//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCALIZACIONE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOCALIZACIONE()
        {
            this.GERENCIAS = new HashSet<GERENCIA>();
            this.OrdenServicios = new HashSet<OrdenServicio>();
            this.OrdenServicios1 = new HashSet<OrdenServicio>();
        }
    
        public int LocCod { get; set; }
        public string LocNom { get; set; }
        public string LocAbr { get; set; }
        public Nullable<int> LocLocCod { get; set; }
        public short LocConCod { get; set; }
        public Nullable<System.DateTime> LocFchCre { get; set; }
        public Nullable<short> LocUsuCodCre { get; set; }
        public Nullable<System.DateTime> LocFchMod { get; set; }
        public Nullable<short> LocUsuCodMod { get; set; }
        public short LocTip { get; set; }
        public Nullable<short> ActiLocCod { get; set; }
        public string LocDim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GERENCIA> GERENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenServicio> OrdenServicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenServicio> OrdenServicios1 { get; set; }
    }
}
