//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG
    {
        public short LogCod { get; set; }
        public short LogConCod { get; set; }
        public short LogAlmCod { get; set; }
        public short LogUsuCod { get; set; }
        public System.DateTime LogFecIni { get; set; }
    }
}
