//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANTTOEVIDENCIA
    {
        public int EmaCod { get; set; }
        public string EmaFol { get; set; }
        public System.DateTime EmaFch { get; set; }
        public int PedCod { get; set; }
        public string EmaObs { get; set; }
        public string EmaCom { get; set; }
        public short EmaAlmCod { get; set; }
    }
}
