//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANTTOREF
    {
        public int MreCod { get; set; }
        public int NotCod { get; set; }
        public int MreProCod { get; set; }
        public short MreCos { get; set; }
        public short MreCan { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual NOTAINFORMATIVA NOTAINFORMATIVA { get; set; }
    }
}
