//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARCA
    {
        public short MarCod { get; set; }
        public string MarDsc { get; set; }
        public Nullable<System.DateTime> MarFchCre { get; set; }
        public Nullable<short> MarUsuCodCre { get; set; }
        public Nullable<System.DateTime> MarFchMod { get; set; }
        public Nullable<short> MarUsuCodMod { get; set; }
    }
}
