//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDIDA
    {
        public short UniCod { get; set; }
        public string UniDsc { get; set; }
        public string UniAbr { get; set; }
        public Nullable<System.DateTime> UniFchCre { get; set; }
        public Nullable<short> UniUsuCodCre { get; set; }
        public Nullable<System.DateTime> UniFchMod { get; set; }
        public Nullable<short> UniUsuCodMod { get; set; }
        public short UniRed { get; set; }
    }
}
