//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public short MenuId { get; set; }
        public string MenuDescription { get; set; }
        public Nullable<short> MenuFatherId { get; set; }
        public string MenuIcon { get; set; }
        public string MenuUrl { get; set; }
        public short MenuTarget { get; set; }
        public Nullable<short> MenuOrd { get; set; }
        public string MenuUrl4 { get; set; }
        public string MenuUrl2 { get; set; }
    }
}
