//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTOSDETALLE
    {
        public int MovCon { get; set; }
        public short ConCod { get; set; }
        public short AlmCod { get; set; }
        public short MovTipDoc { get; set; }
        public System.DateTime MovFch { get; set; }
        public short TPrCod { get; set; }
        public int MovDProCod { get; set; }
        public string MovDNumSer { get; set; }
        public Nullable<int> MovdOrd { get; set; }
        public string MovdVNDITNUM { get; set; }
        public Nullable<decimal> MovdCan { get; set; }
        public Nullable<decimal> MovDCanCon { get; set; }
        public Nullable<decimal> MovDPer { get; set; }
        public Nullable<decimal> MovDDwg { get; set; }
        public Nullable<decimal> MovdCos { get; set; }
        public string MovdTra { get; set; }
        public Nullable<short> MovdNotEnv { get; set; }
        public Nullable<decimal> MovDTieUso { get; set; }
    }
}
