//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTO
    {
        public int MovCon { get; set; }
        public short ConCod { get; set; }
        public short AlmCod { get; set; }
        public short MovTipDoc { get; set; }
        public System.DateTime MovFch { get; set; }
        public short TPrCod { get; set; }
        public int MovCod { get; set; }
        public string MovFol { get; set; }
        public System.DateTime MovHr { get; set; }
        public string MovFac { get; set; }
        public string MovObs { get; set; }
        public string POP10100PONUMBER2 { get; set; }
        public Nullable<int> MovEmpCod { get; set; }
        public Nullable<short> MovEmpComCod { get; set; }
        public Nullable<short> MovEmpPueCod { get; set; }
        public Nullable<int> MovCliEmpCod { get; set; }
        public Nullable<short> MovCliEmpComCod { get; set; }
        public Nullable<short> MovCliEmpPueCod { get; set; }
        public System.DateTime MovFchCre { get; set; }
        public short MovUsuCodCre { get; set; }
        public Nullable<System.DateTime> MovFchMod { get; set; }
        public Nullable<short> MovUsuCodMod { get; set; }
        public Nullable<short> EstCod { get; set; }
        public Nullable<short> MovAlmCod { get; set; }
        public Nullable<int> MovMovCon { get; set; }
        public Nullable<short> MovMovConCod { get; set; }
        public Nullable<short> MovMovAlmCod { get; set; }
        public Nullable<short> MovMovTipDoc { get; set; }
        public Nullable<System.DateTime> MovMovFch { get; set; }
        public Nullable<short> MovVer { get; set; }
        public Nullable<short> MovEsp { get; set; }
        public Nullable<int> EstiCod { get; set; }
        public Nullable<short> MovMovTprCod { get; set; }
        public string MovFchMer { get; set; }
        public Nullable<short> MovExp { get; set; }
    }
}
