//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUNICIPIO
    {
        public short MunCod { get; set; }
        public string MunDsc { get; set; }
        public System.DateTime MunFchCre { get; set; }
        public short MunUsuCod { get; set; }
        public System.DateTime MunFchMod { get; set; }
        public short MunUsuCodMod { get; set; }
        public short EstaCod { get; set; }
    }
}
