//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOMINAEMPRESA
    {
        public short NomCod { get; set; }
        public int EmpCod { get; set; }
        public short EmpComCod { get; set; }
        public Nullable<decimal> NoeBon { get; set; }
        public decimal NoeSDR { get; set; }
        public decimal NoeSD { get; set; }
        public decimal NoeSDI { get; set; }
        public short NoeDiaQui { get; set; }
        public decimal NoeSub { get; set; }
        public decimal NoePriVac { get; set; }
        public Nullable<decimal> NoeCreInf { get; set; }
        public decimal NoeRes { get; set; }
        public decimal NoeCreFon { get; set; }
    }
}
