//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTAINFORMATIVADETALLE
    {
        public int NotCod { get; set; }
        public int NoDProCod { get; set; }
        public decimal NoDCan { get; set; }
        public byte[] NoDArc { get; set; }
        public string NoDArcTip { get; set; }
        public string NoDArcNom { get; set; }
        public Nullable<short> NoDCauDan { get; set; }
        public Nullable<short> CauCod { get; set; }
        public string NoDCauObs { get; set; }
        public Nullable<short> NoDDia { get; set; }
        public Nullable<short> NoDTipMan { get; set; }
        public Nullable<short> NoDOrdSusDes { get; set; }
        public Nullable<short> NoDOrdLub { get; set; }
        public Nullable<short> NoDOrdCal { get; set; }
        public Nullable<short> NoDOrdRef { get; set; }
        public Nullable<short> NodOrdSusDan { get; set; }
        public Nullable<short> NoDOrdRee { get; set; }
        public Nullable<short> NoDOrdPru { get; set; }
        public Nullable<short> NoDOrdAco { get; set; }
        public string NoDDscMan { get; set; }
        public string NoDObsMan { get; set; }
        public byte[] NoDEviMan { get; set; }
        public string NoDEviManNom { get; set; }
        public string NoDEviManTip { get; set; }
        public Nullable<short> NodUsuCodMan { get; set; }
        public Nullable<System.DateTime> NoDFchMan { get; set; }
        public Nullable<short> NoDEstCod { get; set; }
        public string NoDFol { get; set; }
    
        public virtual CAUSA CAUSA { get; set; }
        public virtual ESTATU ESTATU { get; set; }
        public virtual NOTAINFORMATIVA NOTAINFORMATIVA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
