//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCUPACIONCONTENEDORE
    {
        public short OcuCont { get; set; }
        public short OcuAlmCod { get; set; }
        public short ContCod { get; set; }
        public short OcuAct { get; set; }
        public System.DateTime OcuFch { get; set; }
        public string OcuObsr { get; set; }
        public short OcuOpe { get; set; }
        public Nullable<System.DateTime> OcuFchPro { get; set; }
        public Nullable<short> OcuUsuCod { get; set; }
        public System.DateTime OcuFchCre { get; set; }
    }
}
