//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERATIVO
    {
        public int OpeCod { get; set; }
        public short OpeConCod { get; set; }
        public System.DateTime OpeFch { get; set; }
        public string OpeMsg { get; set; }
        public short OpeEqu { get; set; }
        public System.DateTime OpeFchCre { get; set; }
        public System.DateTime OpeFchHr { get; set; }
        public short OpeUsuCod { get; set; }
    }
}
