//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenServicioDesglose
    {
        public string OrdSerFol { get; set; }
        public int OrdSerGProCod { get; set; }
        public decimal OrdSerGCan { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
