//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenServicioRafEstatu
    {
        public string OrdSerFol { get; set; }
        public string OrdSerFolRaf { get; set; }
        public short OrdSerEstCod { get; set; }
        public string OrdSerEstClaRaf { get; set; }
        public System.DateTime OrdSerEstFch { get; set; }
        public decimal OrdSerEstMon { get; set; }
        public string OrdSerEst { get; set; }
    
        public virtual OrdenServicioRaf OrdenServicioRaf { get; set; }
    }
}
