//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenServicioRaf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenServicioRaf()
        {
            this.OrdenServicioRafEstatus = new HashSet<OrdenServicioRafEstatu>();
        }
    
        public string OrdSerFol { get; set; }
        public string OrdSerFolRaf { get; set; }
        public Nullable<System.DateTime> OrdSerFchRaf { get; set; }
        public Nullable<decimal> OrdSerRafMon { get; set; }
        public decimal OrdSerRafMonAct { get; set; }
        public byte[] OrdSerRafArc { get; set; }
        public string OrdSerRafArcTip { get; set; }
        public string OrdSerRafArcNom { get; set; }
        public string OrdSerRafSup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenServicioRafEstatu> OrdenServicioRafEstatus { get; set; }
    }
}
