//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int PedCod { get; set; }
        public string PedFol { get; set; }
        public System.DateTime PedFch { get; set; }
        public System.DateTime PedFchIni { get; set; }
        public Nullable<System.DateTime> PedFchTer { get; set; }
        public short PedAlmCod { get; set; }
        public short PedTConCod { get; set; }
        public short PedEdyCod { get; set; }
        public Nullable<short> PedEqu { get; set; }
        public int PedLocCod { get; set; }
        public int PedSolEmpCod { get; set; }
        public short PedSolEmpComCod { get; set; }
        public int PedAutEmpCod { get; set; }
        public short PedAutEmpComCod { get; set; }
        public int PedTbxEmpCod { get; set; }
        public short PedTbxEmpComCod { get; set; }
        public short PedUsuCodCre { get; set; }
        public System.DateTime PedFchCre { get; set; }
        public Nullable<short> PedUsuCodMod { get; set; }
        public Nullable<System.DateTime> PedFchMod { get; set; }
        public Nullable<short> PedBasCod { get; set; }
        public string PedOrdSer { get; set; }
    }
}
