//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFILESAPLICATIVO
    {
        public int PerCod { get; set; }
        public short AplCod { get; set; }
        public string AplDsc { get; set; }
        public short PerUpd { get; set; }
        public short PerDel { get; set; }
        public short PerCon { get; set; }
        public short PerIns { get; set; }
    }
}
