//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLITICASENTREGA
    {
        public int PolCod { get; set; }
        public short FamCod { get; set; }
        public short SFaCod { get; set; }
        public short PolEppCan { get; set; }
        public short PolEppVig { get; set; }
        public Nullable<System.DateTime> PolEppFch { get; set; }
    }
}
