//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.MANTTOREFs = new HashSet<MANTTOREF>();
            this.NOTAINFORMATIVADETALLEs = new HashSet<NOTAINFORMATIVADETALLE>();
            this.OrdenServicioDesgloses = new HashSet<OrdenServicioDesglose>();
            this.PRODUCTOSUBICACIONs = new HashSet<PRODUCTOSUBICACION>();
        }
    
        public int ProCod { get; set; }
        public short ProTprCod { get; set; }
        public short ProConCod { get; set; }
        public Nullable<decimal> ProPda { get; set; }
        public string ProPdaInt { get; set; }
        public string ProCodPro { get; set; }
        public string ProDsc { get; set; }
        public Nullable<short> UniCod { get; set; }
        public Nullable<short> MarCod { get; set; }
        public Nullable<short> ProvCod { get; set; }
        public Nullable<short> FamCod { get; set; }
        public Nullable<short> SFaCod { get; set; }
        public string ProMod { get; set; }
        public Nullable<short> ProVis { get; set; }
        public string ProNoSer { get; set; }
        public byte[] ProFot { get; set; }
        public string ProFotNom { get; set; }
        public string ProFotTip { get; set; }
        public short ProLin { get; set; }
        public Nullable<System.DateTime> ProFchAlt { get; set; }
        public Nullable<short> ProUsuCodCre { get; set; }
        public Nullable<System.DateTime> ProFchMod { get; set; }
        public Nullable<short> ProUsuCodMod { get; set; }
        public Nullable<decimal> ProComMin { get; set; }
        public Nullable<decimal> ProPreUni { get; set; }
        public Nullable<short> ProTipMon { get; set; }
        public Nullable<short> UbiCod { get; set; }
        public Nullable<int> ProAcu { get; set; }
        public Nullable<int> ProRefProCod { get; set; }
        public Nullable<short> ProMan { get; set; }
        public Nullable<decimal> ProCos { get; set; }
        public Nullable<decimal> ProTal { get; set; }
        public Nullable<decimal> ProComMax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANTTOREF> MANTTOREFs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTAINFORMATIVADETALLE> NOTAINFORMATIVADETALLEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenServicioDesglose> OrdenServicioDesgloses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTOSUBICACION> PRODUCTOSUBICACIONs { get; set; }
    }
}
