//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOSUBICACION
    {
        public int ProUbiCod { get; set; }
        public System.DateTime ProUbiFch { get; set; }
        public string ProUbiFolAct { get; set; }
        public short ProUbiAlmCod { get; set; }
        public string ProUbiFolAnt { get; set; }
        public short ProUbiAlmCodAnt { get; set; }
        public int ProUbiProCod { get; set; }
        public System.DateTime ProUbiFchAct { get; set; }
        public System.DateTime ProUbiFchAnt { get; set; }
        public short ProUbiEstCod { get; set; }
        public string ProUbiObs { get; set; }
        public string ProUbiMovDNumSer { get; set; }
        public string ProUbiModelo { get; set; }
        public Nullable<int> ProUbiOdo { get; set; }
    
        public virtual ALMACENE ALMACENE { get; set; }
        public virtual ALMACENE ALMACENE1 { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
