//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public short ProvCod { get; set; }
        public string ProvNom { get; set; }
        public string ProvDir { get; set; }
        public string ProvRFC { get; set; }
        public string ProvTel1 { get; set; }
        public string ProvTel2 { get; set; }
        public string ProvMail { get; set; }
        public string ProvHttp { get; set; }
        public short ProvPag { get; set; }
        public short ProvMon { get; set; }
        public string ProvCon { get; set; }
        public string ProvTelCon { get; set; }
        public string ProvMailCon { get; set; }
        public Nullable<System.DateTime> ProvFchCre { get; set; }
        public Nullable<short> ProvUsuCodCre { get; set; }
        public Nullable<System.DateTime> ProvFchMod { get; set; }
        public Nullable<short> ProvUsuCodMod { get; set; }
    }
}
