//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUESTO
    {
        public short PueCod { get; set; }
        public string PueDsc { get; set; }
        public System.DateTime PueFchCre { get; set; }
        public short PueUsuCodCre { get; set; }
        public Nullable<System.DateTime> PueFchMod { get; set; }
        public Nullable<short> PueUsuCodMod { get; set; }
    }
}
