//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO
    {
        public int RegCod { get; set; }
        public short RegUsuCod { get; set; }
        public System.DateTime RegFch { get; set; }
        public short RegAni { get; set; }
        public short RegMes { get; set; }
        public short RegCie { get; set; }
        public string RegObs { get; set; }
        public Nullable<short> RegTip { get; set; }
    }
}
