//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUISICIONDETALLE
    {
        public int ReqCod { get; set; }
        public short ReqConCod { get; set; }
        public System.DateTime ReqFch { get; set; }
        public short ReqTip { get; set; }
        public int ReqDProCod { get; set; }
        public decimal ReqDCan { get; set; }
        public string RedDCon { get; set; }
        public string ReqDITEMNMBR { get; set; }
        public Nullable<decimal> ReqDCanOC { get; set; }
    }
}
