//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUISICION
    {
        public int ReqCod { get; set; }
        public short ReqConCod { get; set; }
        public System.DateTime ReqFch { get; set; }
        public short ReqTip { get; set; }
        public string ReqFol { get; set; }
        public short AlmCod { get; set; }
        public short ReqAlmCod { get; set; }
        public short ReqProvCod { get; set; }
        public string ReqObsCom { get; set; }
        public string ReqObs { get; set; }
        public short TPrCod { get; set; }
        public Nullable<System.DateTime> UsuFchMod { get; set; }
        public Nullable<short> UsuCodMod { get; set; }
        public Nullable<System.DateTime> UsuFchCre { get; set; }
        public Nullable<short> UsuCodCre { get; set; }
        public Nullable<System.DateTime> ReqFchOC { get; set; }
        public Nullable<decimal> NumCot { get; set; }
    }
}
