//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RES_ACTIVOS
    {
        public int ActCod { get; set; }
        public short ActConCod { get; set; }
        public short ActFamCod { get; set; }
        public int ResEmpCod { get; set; }
        public short ResEmpComCod { get; set; }
        public System.DateTime ResFch { get; set; }
    }
}
