//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESGUARDO
    {
        public int RguCod { get; set; }
        public System.DateTime RguFch { get; set; }
        public Nullable<short> EdyCod { get; set; }
        public Nullable<short> RguEqu { get; set; }
        public Nullable<int> PedCod { get; set; }
        public string RguObs { get; set; }
        public Nullable<short> RguUsuCodAut { get; set; }
        public Nullable<short> RguUsuCodTec1 { get; set; }
        public Nullable<short> RguUsuCodTec2 { get; set; }
        public short RguTip { get; set; }
    }
}
