//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGURIDADORDEN
    {
        public int SegCod { get; set; }
        public System.DateTime SegOrdFch { get; set; }
        public string SegOrdObs { get; set; }
        public string SegOrdDsc { get; set; }
        public byte[] SegOrdArc { get; set; }
        public string SegOrdArcTip { get; set; }
        public string SegOrdArcNom { get; set; }
        public short SegOrdTip { get; set; }
    }
}
