//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGURIDAD
    {
        public int SegCod { get; set; }
        public System.DateTime SegFch { get; set; }
        public int PedCod { get; set; }
        public byte[] SegEviInsArc { get; set; }
        public string SegEviInsArcTip { get; set; }
        public string SegEviInsArcNom { get; set; }
        public byte[] SegEviDinArc { get; set; }
        public string SegEviDInArcTip { get; set; }
        public string SegEviDInArcNom { get; set; }
    }
}
