//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUV
    {
        public short SvaCod { get; set; }
        public short SvaConCod { get; set; }
        public System.DateTime SvaFch { get; set; }
        public short SvaDiaSol { get; set; }
        public System.DateTime SvaFchIni { get; set; }
        public System.DateTime SvaFchFin { get; set; }
        public System.DateTime SvaFchRea { get; set; }
        public System.DateTime SvaFchPag { get; set; }
        public int SvaCooEmpCod { get; set; }
        public int SvaJefEmpCod { get; set; }
        public short SvaCooComCod { get; set; }
        public short SvaJefComCod { get; set; }
        public string SvaObs { get; set; }
        public short SvaUsuCodCre { get; set; }
        public System.DateTime SvaUsuFchCre { get; set; }
        public Nullable<short> SvaUsuCodUpd { get; set; }
        public Nullable<System.DateTime> SvaUsuFchUpd { get; set; }
        public int SvaEmpCod { get; set; }
        public short SvaEmpComCod { get; set; }
        public byte[] SvaArc { get; set; }
        public string SvaArcNom { get; set; }
        public string SvaArcTip { get; set; }
        public Nullable<short> SvaPerFin { get; set; }
        public Nullable<short> SvaPerIni { get; set; }
    }
}
