//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUDESPEMEX
    {
        public short SolCod { get; set; }
        public string SolUniOpe { get; set; }
        public string SolOfiRaf { get; set; }
        public string SolSup { get; set; }
        public string SiolSit { get; set; }
        public Nullable<decimal> SolMon { get; set; }
        public Nullable<System.DateTime> SolFchPer { get; set; }
    }
}
