//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUSRAF
    {
        public short ID { get; set; }
        public string NoCon { get; set; }
        public string FchReg { get; set; }
        public string NumCtrInt { get; set; }
        public string EstAct { get; set; }
        public string PedSap { get; set; }
        public string ActGer { get; set; }
        public Nullable<decimal> Mont { get; set; }
        public string Paquete { get; set; }
        public string ClaRaf { get; set; }
        public string ClaGral { get; set; }
        public string Clasi { get; set; }
    }
}
