//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOCONT
    {
        public short TConCod { get; set; }
        public string TconTip { get; set; }
        public string TConDsc { get; set; }
        public decimal TConMon { get; set; }
        public short TConConCod { get; set; }
        public Nullable<System.DateTime> TConFchCre { get; set; }
        public Nullable<short> TConUsuCodCre { get; set; }
        public Nullable<System.DateTime> TConFchMod { get; set; }
        public Nullable<short> TConUsuCodMod { get; set; }
        public short TConUniCod { get; set; }
        public int TConProCod { get; set; }
        public Nullable<short> TConCan { get; set; }
    }
}
