//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOPROD
    {
        public short TPrCod { get; set; }
        public string TPrDsc { get; set; }
        public Nullable<System.DateTime> TPrFchCre { get; set; }
        public Nullable<short> TPrUsuCodCre { get; set; }
        public Nullable<System.DateTime> TPrFchMod { get; set; }
        public Nullable<short> TPrUsuCodMod { get; set; }
    }
}
