//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOSCOMPONENTE
    {
        public short UsuCod { get; set; }
        public short WCompNro { get; set; }
        public short DusOrd { get; set; }
        public short DusIzq { get; set; }
    }
}
