//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.EVIDENCIAS = new HashSet<EVIDENCIA>();
            this.Logers = new HashSet<Loger>();
            this.OrdenServicios = new HashSet<OrdenServicio>();
            this.OrdenServicios1 = new HashSet<OrdenServicio>();
        }
    
        public short UsuCod { get; set; }
        public string UsuNom { get; set; }
        public string UsuUse { get; set; }
        public string UsuPas { get; set; }
        public int PerCod { get; set; }
        public System.DateTime UsuFchVig { get; set; }
        public Nullable<short> UsuVer { get; set; }
        public Nullable<int> EmpCod { get; set; }
        public Nullable<short> UsuAut { get; set; }
        public Nullable<short> UsuAlmCod { get; set; }
        public Nullable<short> UsuConCod { get; set; }
        public Nullable<short> EmpComCod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVIDENCIA> EVIDENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loger> Logers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenServicio> OrdenServicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenServicio> OrdenServicios1 { get; set; }
    }
}
