//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALESAUTORIZADO
    {
        public short ValCod { get; set; }
        public int MovCon { get; set; }
        public short ConCod { get; set; }
        public short AlmCod { get; set; }
        public short MovTipDoc { get; set; }
        public System.DateTime MovFch { get; set; }
        public short TPrCod { get; set; }
        public System.DateTime ValFchSol { get; set; }
        public System.DateTime ValFchAut { get; set; }
        public short UsuCod { get; set; }
        public short ValAut { get; set; }
        public short ValUsuCodSol { get; set; }
        public int MovDProCod { get; set; }
        public byte[] ValArcAut { get; set; }
        public string ValArcTip { get; set; }
        public string ValArcNom { get; set; }
    }
}
